FROM node:18-alpine

WORKDIR /app

COPY package.json .

COPY package-lock.json .

RUN npm ci

COPY prisma ./prisma/

COPY . .

EXPOSE 6000

RUN npx prisma generate

RUN npm run build

CMD [ "node dist/main.js" ]